INSERT INTO Modifiers 
	(ModifierId, ModifierType, RunOnce, Permanent, OwnerRequirementSetId, SubjectRequirementSetId)
VALUES	
	--Taj Mahal
	('MAGIL_TAJ_MAHAL_PRODUCTION_BONUS', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', 0, 0, NULL, 'MAGIL_PLAYER_IS_IN_GOLDENAGE_REQUIREMENTS'),
	('MAGIL_TAJ_MAHAL_GOLD_BONUS', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', 0, 0, NULL, 'MAGIL_PLAYER_IS_IN_GOLDENAGE_REQUIREMENTS'),
	('MAGIL_TAJ_MAHAL_SCIENCE_BONUS', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', 0, 0, NULL, 'MAGIL_PLAYER_IS_IN_GOLDENAGE_REQUIREMENTS'),
	('MAGIL_TAJ_MAHAL_CULTURE_BONUS', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', 0, 0, NULL, 'MAGIL_PLAYER_IS_IN_GOLDENAGE_REQUIREMENTS'),
	('MAGIL_TAJ_MAHAL_FAITH_BONUS', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', 0, 0, NULL, 'MAGIL_PLAYER_IS_IN_GOLDENAGE_REQUIREMENTS'),
	('MAGIL_TAJ_MAHAL_GROWTH_BONUS', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_GROWTH', 0, 0, NULL, 'MAGIL_PLAYER_IS_IN_GOLDENAGE_REQUIREMENTS');
	
INSERT INTO ModifierArguments
	(ModifierId, Name, Value, Extra, SecondExtra)
VALUES	
	--Taj Mahal
	('MAGIL_TAJ_MAHAL_PRODUCTION_BONUS', 'YieldType', 'YIELD_PRODUCTION', NULL, NULL),
	('MAGIL_TAJ_MAHAL_PRODUCTION_BONUS', 'Amount', '20', NULL, NULL),	
	('MAGIL_TAJ_MAHAL_GOLD_BONUS', 'YieldType', 'YIELD_GOLD', NULL, NULL),
	('MAGIL_TAJ_MAHAL_GOLD_BONUS', 'Amount', '15', NULL, NULL),	
	('MAGIL_TAJ_MAHAL_SCIENCE_BONUS', 'YieldType', 'YIELD_SCIENCE', NULL, NULL),
	('MAGIL_TAJ_MAHAL_SCIENCE_BONUS', 'Amount', '15', NULL, NULL),	
	('MAGIL_TAJ_MAHAL_CULTURE_BONUS', 'YieldType', 'YIELD_CULTURE', NULL, NULL),
	('MAGIL_TAJ_MAHAL_CULTURE_BONUS', 'Amount', '15', NULL, NULL),	
	('MAGIL_TAJ_MAHAL_FAITH_BONUS', 'YieldType', 'YIELD_FAITH', NULL, NULL),
	('MAGIL_TAJ_MAHAL_FAITH_BONUS', 'Amount', '15', NULL, NULL),
	('MAGIL_TAJ_MAHAL_GROWTH_BONUS', 'Amount', '20', NULL, NULL);

INSERT INTO BuildingModifiers
	(BuildingType, ModifierId)
VALUES	
	--Taj Mahal
	('BUILDING_TAJ_MAHAL', 'MAGIL_TAJ_MAHAL_PRODUCTION_BONUS'),
	('BUILDING_TAJ_MAHAL', 'MAGIL_TAJ_MAHAL_GOLD_BONUS'),
	('BUILDING_TAJ_MAHAL', 'MAGIL_TAJ_MAHAL_SCIENCE_BONUS'),
	('BUILDING_TAJ_MAHAL', 'MAGIL_TAJ_MAHAL_CULTURE_BONUS'),
	('BUILDING_TAJ_MAHAL', 'MAGIL_TAJ_MAHAL_FAITH_BONUS'),
	('BUILDING_TAJ_MAHAL', 'MAGIL_TAJ_MAHAL_GROWTH_BONUS');
	
--RequirementSets
INSERT INTO RequirementSets
	(RequirementSetId,	RequirementSetType)
VALUES	
	('MAGIL_PLAYER_IS_IN_GOLDENAGE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
	(RequirementSetId,	RequirementId)
VALUES	
	('MAGIL_PLAYER_IS_IN_GOLDENAGE_REQUIREMENTS', 'REQUIRES_PLAYER_HAS_GOLDEN_AGE');
