-- Divine Inspiration yield increased
UPDATE ModifierArguments SET Value='8' WHERE ModifierId='DIVINE_INSPIRATION_WONDER_FAITH_MODIFIER' AND Name='Amount';

-- Reliquaries also provides a relic
INSERT INTO Modifiers (ModifierId , ModifierType , RunOnce , Permanent)
	VALUES ('RELIQUARIES_GRANT_RELIC' , 'MODIFIER_PLAYER_GRANT_RELIC' , 1 , 1);	
INSERT INTO ModifierArguments (ModifierId , Name , Value)
	VALUES ('RELIQUARIES_GRANT_RELIC' , 'Amount' , '1');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
	('BUILDING_CRISTO_REDENTOR', 'RELIQUARIES_GRANT_RELIC');

-- Zen Meditation +1 Amenity at 3 Distrcts
INSERT INTO RequirementSets (RequirementSetId , RequirementSetType)
	VALUES ('CITY_FOLLOWS_RELIGION_WITH_3_DISTRICTS_REQUIREMENTS' , 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId)
    VALUES 
	('CITY_FOLLOWS_RELIGION_WITH_3_DISTRICTS_REQUIREMENTS' , 'REQUIRES_CITY_FOLLOWS_RELIGION'),
	('CITY_FOLLOWS_RELIGION_WITH_3_DISTRICTS_REQUIREMENTS' , 'REQUIRES_CITY_HAS_3_SPECIALTY_DISTRICTS');

INSERT INTO Modifiers (ModifierId , ModifierType, SubjectRequirementSetId)
	VALUES 
	('ZEN_MEDITATION_AMENITY_TWO' , 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 'CITY_FOLLOWS_RELIGION_WITH_4_DISTRICTS_REQUIREMENTS'),
	('ZEN_MEDITATION_AMENITY_TWO' , 'MODIFIER_SINGLE_CITY_ADJUST_CITY_AMENITIES_FROM_RELIGION', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value)
	VALUES 
	('ZEN_MEDITATION_AMENITY_TWO' , 'ModifierId' , 'ZEN_MEDITATION_AMENITY_MODIFIER_TWO'),
	('ZEN_MEDITATION_AMENITY_MODIFIER_TWO' , 'Amount' , '1');

INSERT INTO BeliefModifiers (BeliefType , ModifierId)
	VALUES ('BELIEF_ZEN_MEDITATION' , 'ZEN_MEDITATION_AMENITY_TWO');
